version: '3.8'

services:
  person_counter:
    image: moimoi05/person_counting_model-person_counter:latest
    container_name: person_counting_app
    ports:
      - "5000:5000"
    volumes:
      # Sử dụng named volumes để lưu trữ dữ liệu persistent
      - api_data:/app/API
      - student_faces:/app/known_student_faces
      - secrets_data:/app/secrets
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s
    # Uncomment nếu có GPU và muốn sử dụng GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

# Tạo volumes để lưu trữ dữ liệu
volumes:
  api_data:
  student_faces:
  secrets_data:
