# Docker Compose for Student Detection System
# Hướng dẫn sử dụng:
# 1. Đảm bảo Docker và Docker Compose đã được cài đặt
# 2. Chạy: docker compose up -d
# 3. Truy cập: http://localhost:5000

services:
  # Service chính - Student Detection System
  student-detection:
    image: moimoi05/person_counting_model-person_counter:latest
    container_name: student_detection_system
    ports:
      - "5000:5000"
    volumes:
      - ./known_student_faces:/app/known_student_faces
      - ./API:/app/API
    environment:
      - QT_X11_NO_MITSHM=1
    # Để sử dụng camera trên Linux, bỏ comment các dòng bên dưới:
    restart: unless-stopped

    # devices:
    #   - "/dev/video0:/dev/video0"
